version: 2
updates:
  # Golang dependencies
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    # stencil-golang managed dependencies
    ignore:
      - dependency-name: github.com/getoutreach/gobox
      - dependency-name: google.golang.org/grpc
      - dependency-name: github.com/getoutreach/orgservice
      - dependency-name: github.com/getoutreach/services
      - dependency-name: github.com/getoutreach/datastores/v2
      - dependency-name: github.com/getoutreach/tollmon
      - dependency-name: github.com/getoutreach/mint
      - dependency-name: github.com/getoutreach/httpx

  # Ignore semantic-release, this code is only executed in CI.
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "*"

  ## <<Stencil::Block(dependabotPackageManagers)>>

  ## <</Stencil::Block>>
