# example service.yaml
name: vivekshahintro
arguments:
  grpcClients:
    - node
  deployment:
    environments:
      - ops
    serviceDomains:
      - bento
  postgreSQL:
    - name: vivekshahintro
      version: "13.4"
      databaseName: vivekshahintro
      parameterGroupFamily: aurora-postgresql13
      tier: tier-2
      schemas:
        - name: vivekshahintro
          target: Org
  description: Tutorial service for the purpose of enlightenment and enrichment
  lifecycle: in_development
  lintroller: platinum
  metrics: datadog
  opslevel:
    confluenceSpaceKey: https://outreach-io.atlassian.net/wiki/spaces/SP/overview?homepageId=2320568393
  reportingTeam: ce-success-plans-services
  service: true
  serviceActivities:
    - grpc
  tier: 2
  tracing: opentelemetry
  tutorial: true
modules:
  - name: github.com/getoutreach/stencil-base
    channel: rc
  - name: github.com/getoutreach/stencil-golang
    channel: rc
  - name: github.com/getoutreach/devbase
    channel: rc
  - name: github.com/getoutreach/stencil-outreach
    channel: rc
  - name: github.com/getoutreach/stencil-smartstore
    channel: rc
migrated: true
